fixes:
  - "ballerina/grpc/*/::../ballerina/"
  - "ballerina/modules/types.duration/*::../ballerina/"
  - "ballerina/modules/types.struct/*::../ballerina/"
  - "ballerina/modules/types.timestamp/*::../ballerina/"
  - "ballerina/modules/types.wrappers/*::../ballerina/"
  - "ballerina/modules/types.any/*::../ballerina/"

ignore:
  - "grpc-test-utils"
  - "ballerina-tests"
  - "compiler-plugin-tests"
  - "test-utils"
  - "examples"
  - "integration-tests"
  - "load-tests"
  - "ballerina/reflection_pb.bal"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
