fixes:
  - "ballerina/grpc/*::../ballerina/"

ignore:
  - "grpc-test-utils"
  - "ballerina-tests"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
